import com.softwaremill.macwire.Macwire
import play.api.GlobalSettings
import registry.MyRegistry


/**
 * This is the play's global setup controlling class.
 * It is responsible to lookup the controller instances from the registry generated by MacWire
 *
 */
object Global extends GlobalSettings with Macwire {
  private val diRegistry = wiredInModule(MyRegistry)

  /**
   * This method will be called with the class instance from the route configuration file
   */
  override def getControllerInstance[A](controllerClass: Class[A]) = diRegistry.lookupSingleOrThrow(controllerClass)
}